name: nutricare
description: A Flutter mobile app for nutrition care and health tracking.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uni_links: ^0.5.1
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0+1
  shared_preferences: ^2.2.2
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/Logo.png
